# Link the C runtime into the Windows binary, so the game runs on a machine that has
# never installed the Visual C++ redistributable.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
