//! GENERATED by `cargo run --release --bin measure -- --fit --flame`. Do not edit.
//! Per-ancestry target weights that bring neutral heads to adult male norms,
//! and shape gene ranges sized from population SDs. See `src/measure.rs`.

pub const CALIBRATION: [&[(&str, f32)]; 3] = [
    // african
    &[
        ("head/head-fat", -0.055),
        ("mouth/mouth-scale-horiz", 0.344),
        ("chin/chin-height", 0.175),
        ("head/head-scale-vert", 0.196),
        ("head/head-scale-horiz", 0.214),
        ("nose/nose-scale-horiz", 0.189),
        ("nose/nose-scale-vert", -0.019),
        ("eyes/{s}-eye-trans", 0.078),
        ("eyes/{s}-eye-scale", -0.179),
    ],
    // asian
    &[
        ("head/head-fat", 0.043),
        ("mouth/mouth-scale-horiz", 0.543),
        ("chin/chin-height", 0.244),
        ("head/head-scale-vert", 0.116),
        ("head/head-scale-horiz", 0.250),
    ],
    // caucasian
    &[
        ("neck/neck-scale-horiz", -0.500),
        ("head/head-fat", -0.400),
        ("mouth/mouth-scale-horiz", 0.463),
        ("chin/chin-height", 0.059),
        ("chin/chin-bones", -0.600),
        ("head/head-scale-vert", 0.166),
        ("head/head-scale-horiz", 0.147),
        ("nose/nose-scale-horiz", 0.021),
        ("nose/nose-scale-vert", 0.018),
        ("eyes/{s}-eye-trans", -0.500),
        ("eyes/{s}-eye-scale", -0.250),
    ],
];

pub const SHAPE_RANGE: &[(&str, f32)] = &[
    ("head-width", 0.431),
    ("chin-height", 0.587),
    ("eye-size", 0.600),
    ("nose-width", 0.600),
    ("mouth-width", 0.600),
];
