//! GENERATED by `cargo run --release --bin measure -- --fit`. Do not edit.
//! Per-ancestry target weights that bring neutral heads to adult male norms,
//! and shape gene ranges sized from population SDs. See `src/measure.rs`.

pub const CALIBRATION: [&[(&str, f32)]; 3] = [
    // african
    &[
        ("head/head-fat", -0.210),
        ("mouth/mouth-scale-horiz", 0.800),
        ("chin/chin-height", 0.336),
        ("head/head-scale-vert", 0.153),
        ("head/head-scale-horiz", 0.233),
        ("nose/nose-scale-horiz", 0.032),
        ("eyes/{s}-eye-trans", 0.479),
        ("eyes/{s}-eye-scale", -0.250),
    ],
    // asian
    &[
        ("head/head-fat", 0.068),
        ("mouth/mouth-scale-horiz", 0.800),
        ("chin/chin-height", 0.379),
        ("head/head-scale-vert", 0.081),
        ("head/head-scale-horiz", 0.250),
        ("nose/nose-scale-vert", 0.025),
    ],
    // caucasian
    &[
        ("neck/neck-scale-horiz", -0.500),
        ("head/head-fat", -0.400),
        ("mouth/mouth-scale-horiz", 0.800),
        ("chin/chin-height", 0.228),
        ("chin/chin-bones", -0.600),
        ("head/head-scale-vert", 0.131),
        ("head/head-scale-horiz", 0.219),
        ("nose/nose-scale-horiz", -0.159),
        ("nose/nose-scale-vert", 0.034),
        ("eyes/{s}-eye-trans", -0.285),
        ("eyes/{s}-eye-scale", -0.250),
    ],
];

pub const SHAPE_RANGE: &[(&str, f32)] = &[
    ("head-width", 0.431),
    ("chin-height", 0.587),
    ("eye-size", 0.600),
    ("nose-width", 0.600),
    ("mouth-width", 0.600),
];
