//! GENERATED by `cargo run --release --bin measure -- --fit`. Do not edit.
//! Per-ancestry target weights that bring neutral heads to adult male norms,
//! and shape gene ranges sized from population SDs. See `src/measure.rs`.

pub const CALIBRATION: [&[(&str, f32)]; 3] = [
    // african
    &[
        ("mouth/mouth-scale-horiz", 0.311),
        ("chin/chin-height", 0.309),
        ("head/head-scale-vert", 0.153),
        ("head/head-scale-horiz", 0.189),
        ("nose/nose-scale-horiz", 0.217),
        ("eyes/{s}-eye-trans", -0.031),
        ("eyes/{s}-eye-scale", -0.174),
    ],
    // asian
    &[
        ("head/head-fat", 0.068),
        ("mouth/mouth-scale-horiz", 0.514),
        ("chin/chin-height", 0.379),
        ("head/head-scale-vert", 0.081),
        ("head/head-scale-horiz", 0.250),
        ("nose/nose-scale-vert", 0.025),
    ],
    // caucasian
    &[
        ("neck/neck-scale-horiz", -0.500),
        ("head/head-fat", -0.331),
        ("mouth/mouth-scale-horiz", 0.432),
        ("chin/chin-height", 0.164),
        ("chin/chin-bones", -0.600),
        ("head/head-scale-vert", 0.131),
        ("head/head-scale-horiz", 0.118),
        ("nose/nose-scale-horiz", 0.052),
        ("nose/nose-scale-vert", 0.034),
        ("eyes/{s}-eye-trans", -0.500),
        ("eyes/{s}-eye-scale", -0.250),
    ],
];

pub const SHAPE_RANGE: &[(&str, f32)] = &[
    ("head-width", 0.431),
    ("chin-height", 0.587),
    ("eye-size", 0.600),
    ("nose-width", 0.600),
    ("mouth-width", 0.600),
];
